apiVersion: v1
kind: Service
metadata:
  namespace: argo
  name: argo-webhook
spec:
  type: LoadBalancer
  ports:
  - name: webhook
    port: 80
    targetPort: 3000
  selector:
    app: argo-webhook
  type: LoadBalancer
